#!/bin/bash
cmake -B ./build/ -S . && cmake --build ./build/ && mkdir -p ./bin_server/ && cp -r ./base/ ./bin_server/ && cp -r ./config/ ./bin_server/ && mv ./build/exe ./bin_server/exe && echo "Server is compiled and is lying within the bin_server direcrtory with the default config and work(base) directories."
